### ISSUE TITLE
Node-RED on learn.openshift.com

### ISSUE THREAD

**Issue by mark-buckwell** [rhm-samples/node-red-operator#5]
When using the operator on the OpenShift 4.4 playground here https://learn.openshift.com/playgrounds/

The Node-RED operator installed and and I went to create a Node-RED instance but the default YAML does not find the storage class.

Can this either be corrected or instructions created for modifying the YAML for the playground?

**Comment by shrapar** [comment]
Hello Mark,
Can you try creating an instance with out storage? You will have to set this in the "NodeRed" CR 
  persistentvolume:
    enabled: false
Note without storage backup and recovery will not be possible.

**Comment by mark-buckwell** [comment]
Thanks. I made that change and it works. It would be useful to add that to the instructions.

**Comment by kazuhitoyokoi** [comment]
Today, I published two articles about the Node-RED operator on OpenShift.

- How to use Node-RED Operator on RedHat OpenShift
https://kazuhitoyokoi.medium.com/how-to-use-node-red-operator-on-redhat-openshift-e5a516de1e17
- Human pose estimation using Node-RED
https://kazuhitoyokoi.medium.com/human-pose-estimation-using-node-red-69fdb53bd7

The discussion in this issue was helpful for me to write the articles. Thank you!
